INSERT INTO public.content_queue (id, day, publish_date, platforms, type, image_file, caption) VALUES
('day4-phone-tip', 4, '2026-04-14', ARRAY['facebook','instagram'], 'image', 'C4-04-Phone.png',
E'Lost your phone in Colombia?\n\nDon''t panic. Walk into any high-end hotel.\nAsk the lobby to call you a taxi.\n\nDo NOT flag one on the street while distressed.\n\nMore emergency intel in the full survival guide.\n\nmegusta.com.co\n\n#ColombiaTravel #TravelSafety #EmergencyTips #MeGustaColombia #BogotaTravel #MedellinTravel #CartagenaTravel #SoloTravelColombia'),
('day5-bogota-face', 5, '2026-04-21', ARRAY['instagram'], 'image', 'C1-03-Eyes.png',
E'The Bogota Face Protocol.\n\nRule 01: Eyes forward.\nNot scanning the ceiling. Not looking lost.\n\nBogota doesn''t punish tourists for being foreign. It punishes them for being distracted.\n\nThis is from Chapter 1 of the Bogota Survival Vault — 7 chapters of city-specific intel for $17.\n\nmegusta.com.co\n\n#BogotaTravel #ColombiaTravel #MeGustaColombia #NoDarPapaya #TravelTips #ColombiaGuide #SoloTravelColombia #DigitalNomadColombia'),
('day8-phrases', 8, '2026-04-18', ARRAY['facebook','instagram'], 'image', 'C3-03-Script.png',
E'The Front Seat Script.\n\nIn Colombia, always sit in the front of the Uber.\n\nFist bump. Say "Que mas, bien o que?"\n\nSitting in back = "I am a foreign client."\nSitting in front = "I am a friend."\n\nA driver who sees you as a friend protects you and charges you fairly.\n\nThis works in all 3 cities. 27 chapters of intel like this in the Explorer Bundle.\n\nmegusta.com.co\n\n#ColombiaTravel #MeGustaColombia #TravelHack #UberColombia #MedellinTravel #BogotaTravel #CartagenaTravel #NoDarPapaya #SoloTravelColombia'),
('day10-gringo-prices', 10, '2026-04-25', ARRAY['facebook','instagram'], 'image', 'C2-03-Food.png',
E'Lunch in El Poblado, Medellin.\n\nTourist pays: $22\nLocal pays: $8\n\nSame quality. Different neighborhood.\n\nThe free Arrival Cheat Sheet has real prices for Bogota, Medellin & Cartagena.\n\nmegusta.com.co\n\n#MedellinTravel #ColombiaTravel #GringoPrices #MeGustaColombia #FoodColombia #TravelBudget #DigitalNomadColombia #ElPoblado #SoloTravelColombia'),
('day13-redflag', 13, '2026-04-28', ARRAY['facebook','instagram'], 'image', 'C4-03-Robbed.png',
E'If you are robbed in Colombia:\n\nDo not chase.\nDo not fight.\n\nAssets are replaceable.\nYou are not.\n\nFull emergency intel in every city guide.\n\nmegusta.com.co\n\n#ColombiaTravel #TravelSafety #EmergencyTips #MeGustaColombia #NoDarPapaya #SoloTravelColombia #BogotaTravel #MedellinTravel #CartagenaTravel')
ON CONFLICT (id) DO NOTHING;