// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uocwxwvcrnkfnnoyjzyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvY3d4d3Zjcm5rZm5ub3lqenliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyMjU3MzMsImV4cCI6MjA5MDgwMTczM30.CDBPUysRL3-IGe5NNp6YgwJLt9Fu5KSRwV1ELQWiYNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});